"""add sales invoice

Revision ID: 20f789639a3d
Revises: 59e9c0c82f45
Create Date: 2026-01-31 17:07:57.973373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20f789639a3d'
down_revision = '59e9c0c82f45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales_invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('invoice_no', sa.String(length=50), nullable=False),
    sa.Column('customer_name', sa.String(length=120), nullable=False),
    sa.Column('customer_phone', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('ar_account_code', sa.String(length=20), nullable=False),
    sa.Column('ar_account_name', sa.String(length=120), nullable=False),
    sa.Column('revenue_account_code', sa.String(length=20), nullable=False),
    sa.Column('revenue_account_name', sa.String(length=120), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('paid_amount', sa.Float(), nullable=False),
    sa.Column('journal_entry_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_no')
    )
    op.create_table('sales_invoice_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['sales_invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sales_invoice_lines')
    op.drop_table('sales_invoices')
    # ### end Alembic commands ###
