"""initial schema

Revision ID: 54b4baa96824
Revises: 
Create Date: 2026-02-07 17:42:10.523962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54b4baa96824'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=24), nullable=False),
    sa.Column('dapur_name', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('start_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('access_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_access_codes_code'), ['code'], unique=True)

    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access_code_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['access_code_id'], ['access_codes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('access_code_id', 'code', name='uq_accounts_tenant_code')
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accounts_access_code_id'), ['access_code_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounts_code'), ['code'], unique=False)

    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access_code_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('min_stock', sa.Float(), nullable=False),
    sa.Column('stock_qty', sa.Float(), nullable=False),
    sa.Column('avg_cost', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['access_code_id'], ['access_codes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('access_code_id', 'name', name='uq_items_tenant_name')
    )
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_items_access_code_id'), ['access_code_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_name'), ['name'], unique=False)

    op.create_table('journal_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access_code_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('memo', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['access_code_id'], ['access_codes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journal_entries_access_code_id'), ['access_code_id'], unique=False)

    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access_code_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['access_code_id'], ['access_codes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('access_code_id', 'name', name='uq_suppliers_tenant_name')
    )
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suppliers_access_code_id'), ['access_code_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_suppliers_name'), ['name'], unique=False)

    op.create_table('cash_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access_code_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('direction', sa.String(length=5), nullable=False),
    sa.Column('cash_account_code', sa.String(length=10), nullable=False),
    sa.Column('cash_account_name', sa.String(length=120), nullable=False),
    sa.Column('counter_account_code', sa.String(length=10), nullable=False),
    sa.Column('counter_account_name', sa.String(length=120), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('memo', sa.String(length=255), nullable=True),
    sa.Column('journal_entry_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['access_code_id'], ['access_codes.id'], ),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cash_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cash_transactions_access_code_id'), ['access_code_id'], unique=False)

    op.create_table('journal_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access_code_id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('account_code', sa.String(length=10), nullable=False),
    sa.Column('account_name', sa.String(length=120), nullable=False),
    sa.Column('debit', sa.Float(), nullable=False),
    sa.Column('credit', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['access_code_id'], ['access_codes.id'], ),
    sa.ForeignKeyConstraint(['entry_id'], ['journal_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('journal_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journal_lines_access_code_id'), ['access_code_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_lines_account_code'), ['account_code'], unique=False)
        batch_op.create_index('ix_journal_lines_tenant_account', ['access_code_id', 'account_code'], unique=False)

    op.create_table('purchases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access_code_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('supplier_name', sa.String(length=120), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('journal_entry_id', sa.Integer(), nullable=True),
    sa.Column('memo', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['access_code_id'], ['access_codes.id'], ),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchases_access_code_id'), ['access_code_id'], unique=False)

    op.create_table('sales_invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access_code_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('invoice_no', sa.String(length=50), nullable=False),
    sa.Column('customer_name', sa.String(length=120), nullable=False),
    sa.Column('customer_phone', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('ar_account_code', sa.String(length=20), nullable=False),
    sa.Column('ar_account_name', sa.String(length=120), nullable=False),
    sa.Column('revenue_account_code', sa.String(length=20), nullable=False),
    sa.Column('revenue_account_name', sa.String(length=120), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('paid_amount', sa.Float(), nullable=False),
    sa.Column('journal_entry_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['access_code_id'], ['access_codes.id'], ),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('access_code_id', 'invoice_no', name='uq_sales_invoices_tenant_invoice_no')
    )
    with op.batch_alter_table('sales_invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_invoices_access_code_id'), ['access_code_id'], unique=False)

    op.create_table('stock_usages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access_code_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=120), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('unit_cost', sa.Float(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('hpp_account_code', sa.String(length=10), nullable=False),
    sa.Column('hpp_account_name', sa.String(length=120), nullable=False),
    sa.Column('memo', sa.String(length=255), nullable=True),
    sa.Column('journal_entry_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['access_code_id'], ['access_codes.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_usages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_usages_access_code_id'), ['access_code_id'], unique=False)

    op.create_table('ap_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access_code_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('purchase_id', sa.Integer(), nullable=True),
    sa.Column('supplier_name', sa.String(length=120), nullable=True),
    sa.Column('cash_account_code', sa.String(length=10), nullable=False),
    sa.Column('cash_account_name', sa.String(length=120), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('memo', sa.String(length=255), nullable=True),
    sa.Column('journal_entry_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['access_code_id'], ['access_codes.id'], ),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], ),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ap_payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ap_payments_access_code_id'), ['access_code_id'], unique=False)

    op.create_table('ar_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access_code_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('invoice_no', sa.String(length=50), nullable=False),
    sa.Column('cash_account_code', sa.String(length=20), nullable=False),
    sa.Column('cash_account_name', sa.String(length=120), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('memo', sa.String(length=255), nullable=True),
    sa.Column('journal_entry_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['access_code_id'], ['access_codes.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['sales_invoices.id'], ),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ar_payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ar_payments_access_code_id'), ['access_code_id'], unique=False)

    op.create_table('purchase_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access_code_id', sa.Integer(), nullable=False),
    sa.Column('purchase_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=120), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['access_code_id'], ['access_codes.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_items_access_code_id'), ['access_code_id'], unique=False)

    op.create_table('sales_invoice_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access_code_id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['access_code_id'], ['access_codes.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['sales_invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sales_invoice_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_invoice_lines_access_code_id'), ['access_code_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_invoice_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_invoice_lines_access_code_id'))

    op.drop_table('sales_invoice_lines')
    with op.batch_alter_table('purchase_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_items_access_code_id'))

    op.drop_table('purchase_items')
    with op.batch_alter_table('ar_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ar_payments_access_code_id'))

    op.drop_table('ar_payments')
    with op.batch_alter_table('ap_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ap_payments_access_code_id'))

    op.drop_table('ap_payments')
    with op.batch_alter_table('stock_usages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_usages_access_code_id'))

    op.drop_table('stock_usages')
    with op.batch_alter_table('sales_invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_invoices_access_code_id'))

    op.drop_table('sales_invoices')
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchases_access_code_id'))

    op.drop_table('purchases')
    with op.batch_alter_table('journal_lines', schema=None) as batch_op:
        batch_op.drop_index('ix_journal_lines_tenant_account')
        batch_op.drop_index(batch_op.f('ix_journal_lines_account_code'))
        batch_op.drop_index(batch_op.f('ix_journal_lines_access_code_id'))

    op.drop_table('journal_lines')
    with op.batch_alter_table('cash_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cash_transactions_access_code_id'))

    op.drop_table('cash_transactions')
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suppliers_name'))
        batch_op.drop_index(batch_op.f('ix_suppliers_access_code_id'))

    op.drop_table('suppliers')
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journal_entries_access_code_id'))

    op.drop_table('journal_entries')
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_items_name'))
        batch_op.drop_index(batch_op.f('ix_items_access_code_id'))

    op.drop_table('items')
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounts_code'))
        batch_op.drop_index(batch_op.f('ix_accounts_access_code_id'))

    op.drop_table('accounts')
    with op.batch_alter_table('access_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_access_codes_code'))

    op.drop_table('access_codes')
    # ### end Alembic commands ###
