"""add ap payment

Revision ID: 77d44a6a35d9
Revises: 02ec7e60a852
Create Date: 2026-01-31 13:11:02.087555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77d44a6a35d9'
down_revision = '02ec7e60a852'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ap_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('purchase_id', sa.Integer(), nullable=True),
    sa.Column('supplier_name', sa.String(length=120), nullable=True),
    sa.Column('cash_account_code', sa.String(length=10), nullable=False),
    sa.Column('cash_account_name', sa.String(length=120), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('memo', sa.String(length=255), nullable=True),
    sa.Column('journal_entry_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], ),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ap_payments')
    # ### end Alembic commands ###
